### ISSUE TITLE
[Question]: Use settings in a resource page

### ISSUE THREAD

**Issue by plantjes** [Quadrubo/filament-model-settings#6]
### What happened?

Hi, can I use this for a specific resource? 
For example I have a schools model with the settings table column. In my school resource I want to add school specific field settings.

### How to reproduce the bug

..

### Package Version

1.0

### PHP Version

8.1

### Laravel Version

10

**Comment by Quadrubo** [comment]
By design of the underlying package https://github.com/glorand/laravel-model-settings, the settings are stored in a json field. As you can use multiple settings, you'd have to create a form field for each of those. 

What is your usecase, how do you expect the "school specific field settings" to work.
- Do you want a single field for each of those and just use them on your create/update page?
- Do you want a single settings field that maybe open's a modal or something like that?

Maybe you can share the settings of the `School` model so I can imagine this better :)

**Comment by plantjes** [comment]
If I read the documentation then setting form fields are only possible on a specific settings page. 
What I want is adding setting form fields to a School resource (besides the normal form fields), so I can save specific settings for school ID 1 and can register default values

For example I have a School resource:

- Tabgroup: Global
-- Field: Name (School model -> name)
-- Field: Logo (School model -> logo)
- Tabgroup: Settings (School model -> settings json)
-- Field (setting): School color 1
-- Field (setting): School color 2
-- Field (setting): School color 3
-- Field (setting): School can add students yes/no
-- Field (setting): School can add members

In my School model I only have 1 column with the json field "settings". I don't want a column for each setting field.

**Comment by Quadrubo** [comment]
I have implemented this in #8. It will be in the next release.

**Comment by Quadrubo** [comment]
This is implemented in release v1.1.0

**Comment by plantjes** [comment]
Thank you!
